# Run this Docker compose file using `docker-compose up -d --build`
# No need specify version 2 or 3 in latest Compose specification

services:
  # Backend service (FastAPI, Pycaret and streamlit deployment)
  backend:
    build: backend
    image: fastapi-backend:latest     
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    networks:
      - project_network

  # Frontend service (Streamlit UI)
  frontend:
    build: frontend
    image: streamlit-frontend:latest
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on: 
    - backend
    networks:
      - project_network

networks:
  project_network: